### PR TITLE
Plot inset util code

### PR DESCRIPTION
**Pull request by Andrewwango**
Util code for plotting images with insets (often useful for highlighting restoration/reconstruction results). Thanks to @jscanvic for helping with this. Example of plots produced using this code: https://andrewwango.github.io/perspective-equivariant-imaging/demo.html#results

### Checks to be done before submitting your PR
- [x] `python3 -m pytest tests/` runs successfully.
- [x] `black .` runs successfully.
- [x] `make html` runs successfully (in the `docs/` directory).
- [x] Updated docstrings related to the changes (as applicable).
- [ ] Added an entry to the [CHANGELOG.rst](../CHANGELOG.rst).

### CODE REVIEW

**Comment by samuro95** [comment]
Could plot_inset be an option of the previous plot function ?

**Comment by Andrewwango** [comment]
> Could plot_inset be an option of the previous plot function ?

It could do, but it will mean `plot` has a lot of unnecessary parameters for most users (unless we put all the inset locations etc. in a dict or some kwargs)

**Comment by samuro95** [comment]
I think the dict could be the best solution indeed !

**Review by tachella — APPROVED** [review]
cool addition to the plotting utils of the library, thanks for suggesting this.
I think it is best to keep it separate from plot, to avoid having a monster plot function

**Pull request merged**
