### PR TITLE
add explicit msg for import error for optional module needed in some …

### PR DESCRIPTION
**Pull request by MaximeSongIdris**
[…datasets](https://github.com/deepinv/deepinv/issues/283)

### Checks to be done before submitting your PR
- [ ] `python3 -m pytest tests/` runs successfully.
- [x] `black .` runs successfully.
- [ ] `make html` runs successfully (in the `docs/` directory).
- [ ] Updated docstrings related to the changes (as applicable).
- [ ] Added an entry to the [CHANGELOG.rst](../CHANGELOG.rst).

### CODE REVIEW

**Comment by Andrewwango** [comment]
Can we not just make `datasets` optional completely e.g. by putting it in the CBSD68 init? Because this will still result in an error if I want to use deepinv but not these datasets and don't want to install `datasets`

**Review by tachella — COMMENTED** [review]
@Andrewwango is this solving the issues you were having?

**Comment by MaximeSongIdris** [comment]
@Andrewwango 
yes I prefer to have the import at the start of the file, the diff is that I stored the import error in a variable which will be called in __init__ (so the import error will be raised when instantiating the class) and it shouldn't cause any issue with the library if you don't call the class

also added in README, command line to install the library with the optional dependencies

**Review by Andrewwango — APPROVED** [review]
Looks good, thanks

**Comment by Andrewwango** [comment]
Closes #283

**Pull request merged**
